# Generated by Django 3.1.5 on 2021-01-26 15:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='portalapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalquestions', models.PositiveIntegerField()),
                ('totalmarks', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('duration', models.TimeField()),
                ('starttime', models.DateTimeField()),
                ('obtainedmarks', models.PositiveIntegerField()),
                ('course', models.ManyToManyField(related_name='exams', to='portalapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('iscorrect', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrueFalse', to='portalapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='students', through='portalapp.Enrollment', to='portalapp.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiCorrectMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('incorrect', models.PositiveIntegerField()),
                ('ispartial', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultiCorrectMCQ', to='portalapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCQ', to='portalapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscorrect', models.BooleanField()),
                ('text', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portalapp.multicorrectmcq')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('answer', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integer', to='portalapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='FillBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=30)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FillBlanks', to='portalapp.exam')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='portalapp.student'),
        ),
        migrations.CreateModel(
            name='Descriptive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('maxmarks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('answer', models.CharField(blank=True, max_length=1000)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descriptive', to='portalapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscorrect', models.BooleanField()),
                ('text', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portalapp.mcq')),
            ],
        ),
    ]
