# Generated by Django 3.1.5 on 2021-02-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_auto_20210130_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='studentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='obtainedmarks',
            new_name='total_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='totalmarks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='totalquestions',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='exam', max_length=256),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.courses'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
